# Generated by Django 5.2.7 on 2025-11-05 01:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_status_transaction_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
